version: '3.8'

services:
  api:
    build: ./api
    container_name: foodtruck_api
    environment:
      - REDIS_URL=redis://engineering_assessment_redis:6379
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: engineering_assessment_redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: foodtruck_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - api
